package meditrack.ui.screen;

import java.io.IOException;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;

import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import meditrack.logic.RosterAutoGenerator;
import meditrack.logic.commands.exceptions.CommandException;
import meditrack.model.DutySlot;
import meditrack.model.DutyType;
import meditrack.model.ModelManager;
import meditrack.model.Personnel;
import meditrack.model.Status;
import meditrack.storage.StorageManager;

/**
 * Duty Roster screen — schedule FIT personnel into named duty slots with time windows.
 *
 * <p>Supports two workflows:
 * <ul>
 *   <li><b>Manual</b>: fill in the add-slot form and click "Add Slot".</li>
 *   <li><b>Auto-generate</b>: click "Auto-Generate" to open a dialog that schedules
 *       selected duty types automatically, respecting the 8-hour break rule.</li>
 * </ul>
 *
 * <p>Every row in the table has <b>Edit</b> and <b>Remove</b> action buttons.
 * All changes are persisted to {@code data.json} immediately.
 *
 * <p>Only visible to Platoon Commanders (enforced by the sidebar).
 */
public class DutyRosterScreen extends VBox {

    private final ModelManager model;
    private final StorageManager storage;

    // -- Form inputs --
    private final TextField startField = new TextField();
    private final TextField endField = new TextField();
    private final ComboBox<DutyType> dutyTypeCombo = new ComboBox<>();
    private final ComboBox<String> personnelCombo = new ComboBox<>();
    private final Label formErrorLabel = new Label();

    // -- Table --
    private final TableView<DutySlot> table = new TableView<>();
    private final Label headlineLabel = new Label();

    /**
     * @param model   used to read personnel and manage duty slots
     * @param storage used to persist changes after each mutation
     */
    public DutyRosterScreen(ModelManager model, StorageManager storage) {
        this.model = model;
        this.storage = storage;
        buildUi();
    }

    /** Call this whenever the screen is shown to sync with current model state. */
    public void refresh() {
        refreshPersonnelCombo();
        refreshTable();
    }

    // -------------------------------------------------------------------------
    // UI construction
    // -------------------------------------------------------------------------

    @SuppressWarnings("unchecked")
    private void buildUi() {
        setSpacing(14);
        setPadding(new Insets(20));

        // Title row
        Label title = new Label("Duty Roster");
        title.setStyle("-fx-font-size: 18px; -fx-font-weight: bold;");

        Button autoGenBtn = new Button("Auto-Generate");
        autoGenBtn.setStyle("-fx-background-color: #6610f2; -fx-text-fill: white; "
                + "-fx-font-weight: bold; -fx-padding: 7 16 7 16; -fx-background-radius: 5;");
        autoGenBtn.setOnAction(e -> showAutoGenerateDialog());

        HBox titleRow = new HBox(12, title, autoGenBtn);
        titleRow.setAlignment(Pos.CENTER_LEFT);

        headlineLabel.setStyle("-fx-font-size: 13px; -fx-text-fill: #555;");

        // Add-slot form
        startField.setPromptText("Start (HH:mm)");
        startField.setPrefWidth(110);
        endField.setPromptText("End   (HH:mm)");
        endField.setPrefWidth(110);

        dutyTypeCombo.setItems(FXCollections.observableArrayList(DutyType.values()));
        dutyTypeCombo.setPromptText("Duty Type");
        dutyTypeCombo.setPrefWidth(155);

        personnelCombo.setPromptText("Assign Personnel");
        personnelCombo.setPrefWidth(175);

        Button addBtn = new Button("Add Slot");
        addBtn.setStyle("-fx-background-color: #198754; -fx-text-fill: white; "
                + "-fx-font-weight: bold; -fx-padding: 7 16 7 16; -fx-background-radius: 5;");
        addBtn.setOnAction(e -> handleAdd());

        formErrorLabel.setStyle("-fx-text-fill: #dc3545; -fx-font-size: 12px;");
        formErrorLabel.setVisible(false);
        formErrorLabel.setManaged(false);

        Label addLabel = new Label("Add Duty Slot:");
        addLabel.setStyle("-fx-font-weight: bold; -fx-font-size: 13px;");

        HBox formRow = new HBox(10,
                startField, new Label("->"), endField,
                dutyTypeCombo, personnelCombo, addBtn);
        formRow.setAlignment(Pos.CENTER_LEFT);

        VBox formBox = new VBox(6, addLabel, formRow, formErrorLabel);
        formBox.setPadding(new Insets(12));
        formBox.setStyle("-fx-background-color: white; -fx-background-radius: 8; "
                + "-fx-border-color: #dee2e6; -fx-border-radius: 8;");

        // Table
        TableColumn<DutySlot, String> timeCol = new TableColumn<>("Time Slot");
        timeCol.setCellValueFactory(data ->
                new javafx.beans.property.SimpleStringProperty(
                        data.getValue().getTimeSlotDisplay()));
        timeCol.setPrefWidth(140);
        timeCol.setSortable(false);

        TableColumn<DutySlot, String> typeCol = new TableColumn<>("Duty Type");
        typeCol.setCellValueFactory(data ->
                new javafx.beans.property.SimpleStringProperty(
                        data.getValue().getDutyType().toString()));
        typeCol.setPrefWidth(145);
        typeCol.setSortable(false);

        TableColumn<DutySlot, String> personCol = new TableColumn<>("Personnel");
        personCol.setCellValueFactory(data ->
                new javafx.beans.property.SimpleStringProperty(
                        data.getValue().getPersonnelName()));
        personCol.setPrefWidth(145);
        personCol.setSortable(false);

        TableColumn<DutySlot, Void> actionCol = buildActionColumn();
        actionCol.setPrefWidth(160);
        actionCol.setSortable(false);

        table.getColumns().addAll(timeCol, typeCol, personCol, actionCol);
        table.setPlaceholder(new Label("No duty slots scheduled yet."));
        table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN);

        // Bottom row
        Button clearBtn = new Button("Clear All");
        clearBtn.setStyle("-fx-background-color: #6c757d; -fx-text-fill: white; "
                + "-fx-font-weight: bold; -fx-padding: 7 16 7 16; -fx-background-radius: 5;");
        clearBtn.setOnAction(e -> handleClearAll());

        HBox bottomRow = new HBox(clearBtn);
        bottomRow.setAlignment(Pos.CENTER_RIGHT);

        getChildren().addAll(titleRow, formBox, headlineLabel, table, bottomRow);
        VBox.setVgrow(table, Priority.ALWAYS);
    }

    /** Builds the combined Edit + Remove action column. */
    private TableColumn<DutySlot, Void> buildActionColumn() {
        TableColumn<DutySlot, Void> col = new TableColumn<>("Actions");
        col.setCellFactory(c -> new TableCell<>() {
            private final Button editBtn   = new Button("Edit");
            private final Button removeBtn = new Button("Remove");
            private final HBox box = new HBox(6, editBtn, removeBtn);

            {
                editBtn.setStyle("-fx-background-color: #0d6efd; -fx-text-fill: white; "
                        + "-fx-font-size: 11px; -fx-padding: 3 10 3 10; -fx-background-radius: 4;");
                removeBtn.setStyle("-fx-background-color: #dc3545; -fx-text-fill: white; "
                        + "-fx-font-size: 11px; -fx-padding: 3 10 3 10; -fx-background-radius: 4;");
                box.setAlignment(Pos.CENTER_LEFT);

                editBtn.setOnAction(e -> {
                    int idx = getIndex();
                    if (idx >= 0 && idx < table.getItems().size()) {
                        handleEdit(idx, table.getItems().get(idx));
                    }
                });
                removeBtn.setOnAction(e -> {
                    int idx = getIndex();
                    if (idx >= 0 && idx < table.getItems().size()) {
                        handleRemove(idx);
                    }
                });
            }

            @Override
            protected void updateItem(Void item, boolean empty) {
                super.updateItem(item, empty);
                setGraphic(empty ? null : box);
            }
        });
        return col;
    }

    // -------------------------------------------------------------------------
    // Event handlers
    // -------------------------------------------------------------------------

    private void handleAdd() {
        clearFormError();

        LocalTime start;
        LocalTime end;
        try {
            start = LocalTime.parse(startField.getText().trim());
        } catch (DateTimeParseException e) {
            showFormError("Invalid start time - use HH:mm (e.g. 08:00).");
            return;
        }
        try {
            end = LocalTime.parse(endField.getText().trim());
        } catch (DateTimeParseException e) {
            showFormError("Invalid end time - use HH:mm (e.g. 10:00).");
            return;
        }

        DutyType type = dutyTypeCombo.getValue();
        if (type == null) {
            showFormError("Please select a duty type.");
            return;
        }
        String person = personnelCombo.getValue();
        if (person == null || person.isBlank()) {
            showFormError("Please select a personnel member.");
            return;
        }

        model.addDutySlot(new DutySlot(start, end, type, person));
        persist();
        refreshTable();
        clearForm();
    }

    private void handleRemove(int zeroBasedIndex) {
        try {
            model.removeDutySlot(zeroBasedIndex);
            persist();
            refreshTable();
        } catch (CommandException ex) {
            showFormError(ex.getMessage());
        }
    }

    private void handleEdit(int zeroBasedIndex, DutySlot existing) {
        List<String> fitNames = model.getFilteredPersonnelList(Status.FIT)
                .stream().map(Personnel::getName).toList();

        ComboBox<DutyType> typeCombo = new ComboBox<>(
                FXCollections.observableArrayList(DutyType.values()));
        typeCombo.setValue(existing.getDutyType());

        ComboBox<String> nameCombo = new ComboBox<>(
                FXCollections.observableArrayList(fitNames));
        nameCombo.setValue(existing.getPersonnelName());

        Label errLabel = new Label();
        errLabel.setStyle("-fx-text-fill: #dc3545; -fx-font-size: 11px;");
        errLabel.setVisible(false);
        errLabel.setManaged(false);

        GridPane grid = new GridPane();
        grid.setHgap(12);
        grid.setVgap(10);
        grid.setPadding(new Insets(16, 24, 8, 24));
        grid.add(new Label("Time:"), 0, 0);
        grid.add(new Label(existing.getTimeSlotDisplay()), 1, 0);
        grid.add(new Label("Duty Type:"), 0, 1);
        grid.add(typeCombo, 1, 1);
        grid.add(new Label("Personnel:"), 0, 2);
        grid.add(nameCombo, 1, 2);
        grid.add(errLabel, 0, 3, 2, 1);

        ColumnConstraints c1 = new ColumnConstraints();
        c1.setMinWidth(80);
        ColumnConstraints c2 = new ColumnConstraints();
        c2.setMinWidth(180);
        c2.setHgrow(Priority.ALWAYS);
        grid.getColumnConstraints().addAll(c1, c2);

        Dialog<ButtonType> dialog = new Dialog<>();
        dialog.setTitle("Edit Duty Slot");
        dialog.setHeaderText("Modify the duty type or assigned personnel.");
        dialog.getDialogPane().setContent(grid);
        dialog.getDialogPane().getButtonTypes().addAll(ButtonType.OK, ButtonType.CANCEL);

        Button okBtn = (Button) dialog.getDialogPane().lookupButton(ButtonType.OK);
        okBtn.addEventFilter(javafx.event.ActionEvent.ACTION, ev -> {
            if (typeCombo.getValue() == null) {
                errLabel.setText("Please select a duty type.");
                errLabel.setVisible(true);
                errLabel.setManaged(true);
                ev.consume();
            } else if (nameCombo.getValue() == null || nameCombo.getValue().isBlank()) {
                errLabel.setText("Please select a personnel member.");
                errLabel.setVisible(true);
                errLabel.setManaged(true);
                ev.consume();
            }
        });

        dialog.showAndWait().ifPresent(btn -> {
            if (btn == ButtonType.OK) {
                DutySlot updated = new DutySlot(
                        existing.getStartTime(),
                        existing.getEndTime(),
                        typeCombo.getValue(),
                        nameCombo.getValue());
                try {
                    model.replaceDutySlot(zeroBasedIndex, updated);
                    persist();
                    refreshTable();
                } catch (CommandException ex) {
                    showFormError(ex.getMessage());
                }
            }
        });
    }

    private void handleClearAll() {
        if (model.getDutySlots().isEmpty()) {
            return;
        }
        Alert confirm = new Alert(Alert.AlertType.CONFIRMATION,
                "Remove all " + model.getDutySlots().size() + " duty slot(s)?",
                ButtonType.YES, ButtonType.NO);
        confirm.setTitle("Clear Duty Roster");
        confirm.setHeaderText(null);
        confirm.showAndWait().ifPresent(btn -> {
            if (btn == ButtonType.YES) {
                model.clearDutySlots();
                persist();
                refreshTable();
            }
        });
    }

    // -------------------------------------------------------------------------
    // Auto-generate dialog
    // -------------------------------------------------------------------------

    private void showAutoGenerateDialog() {
        List<Personnel> fitPersonnel = model.getFilteredPersonnelList(Status.FIT);
        if (fitPersonnel.isEmpty()) {
            showFormError("No FIT personnel available for auto-generation.");
            return;
        }

        // Checkboxes for each duty type
        List<CheckBox> typeBoxes = new ArrayList<>();
        for (DutyType type : DutyType.values()) {
            CheckBox cb = new CheckBox(type.toString());
            cb.setSelected(type == DutyType.GUARD_DUTY || type == DutyType.MEDICAL_COVER);
            typeBoxes.add(cb);
        }

        // Replace vs Append
        ToggleGroup modeGroup = new ToggleGroup();
        RadioButton replaceRb = new RadioButton("Replace existing slots");
        RadioButton appendRb  = new RadioButton("Append to existing slots");
        replaceRb.setToggleGroup(modeGroup);
        appendRb.setToggleGroup(modeGroup);
        replaceRb.setSelected(true);

        Label coverageNote = new Label(
                "Guard Duty & Patrol: 00:00 - 00:00 (24 h)\n"
                + "All other types:     08:00 - 20:00 (12 h)\n"
                + "Each person is guaranteed >= 8 h continuous break.");
        coverageNote.setStyle("-fx-text-fill: #6c757d; -fx-font-size: 11px;");

        Label fitNote = new Label("FIT personnel available: " + fitPersonnel.size());
        fitNote.setStyle("-fx-font-weight: bold;");

        Label errLabel = new Label();
        errLabel.setStyle("-fx-text-fill: #dc3545; -fx-font-size: 11px;");
        errLabel.setVisible(false);
        errLabel.setManaged(false);

        VBox content = new VBox(10);
        content.setPadding(new Insets(16, 24, 8, 24));
        content.getChildren().add(fitNote);
        content.getChildren().add(new Label("Duty types to schedule:"));
        content.getChildren().addAll(typeBoxes);
        content.getChildren().add(new Separator());
        content.getChildren().addAll(replaceRb, appendRb);
        content.getChildren().add(new Separator());
        content.getChildren().add(coverageNote);
        content.getChildren().add(errLabel);

        Dialog<ButtonType> dialog = new Dialog<>();
        dialog.setTitle("Auto-Generate Duty Roster");
        dialog.setHeaderText("Generate duty slots for all FIT personnel.");
        dialog.getDialogPane().setContent(content);
        dialog.getDialogPane().getButtonTypes().addAll(ButtonType.OK, ButtonType.CANCEL);
        dialog.getDialogPane().setPrefWidth(400);

        Button okBtn = (Button) dialog.getDialogPane().lookupButton(ButtonType.OK);
        okBtn.setText("Generate");
        okBtn.addEventFilter(javafx.event.ActionEvent.ACTION, ev -> {
            boolean anySelected = typeBoxes.stream().anyMatch(CheckBox::isSelected);
            if (!anySelected) {
                errLabel.setText("Select at least one duty type.");
                errLabel.setVisible(true);
                errLabel.setManaged(true);
                ev.consume();
            }
        });

        dialog.showAndWait().ifPresent(btn -> {
            if (btn != ButtonType.OK) {
                return;
            }

            List<DutyType> selected = new ArrayList<>();
            DutyType[] allTypes = DutyType.values();
            for (int i = 0; i < allTypes.length; i++) {
                if (typeBoxes.get(i).isSelected()) {
                    selected.add(allTypes[i]);
                }
            }

            List<String> names = fitPersonnel.stream()
                    .map(Personnel::getName).toList();
            List<DutySlot> generated = RosterAutoGenerator.generate(names, selected);

            if (replaceRb.isSelected()) {
                model.clearDutySlots();
            }
            for (DutySlot slot : generated) {
                model.addDutySlot(slot);
            }
            persist();
            refreshTable();
            clearFormError();
        });
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private void refreshTable() {
        List<DutySlot> slots = model.getDutySlots();
        table.setItems(FXCollections.observableArrayList(slots));
        int count = slots.size();
        headlineLabel.setText(count == 0
                ? "No duty slots scheduled yet."
                : count + " duty slot" + (count == 1 ? "" : "s") + " scheduled.");
    }

    private void refreshPersonnelCombo() {
        List<Personnel> fit = model.getFilteredPersonnelList(Status.FIT);
        List<String> names = fit.stream().map(Personnel::getName).toList();
        personnelCombo.setItems(FXCollections.observableArrayList(names));
    }

    private void clearForm() {
        startField.clear();
        endField.clear();
        dutyTypeCombo.setValue(null);
        personnelCombo.setValue(null);
    }

    private void showFormError(String msg) {
        formErrorLabel.setText("!  " + msg);
        formErrorLabel.setVisible(true);
        formErrorLabel.setManaged(true);
    }

    private void clearFormError() {
        formErrorLabel.setVisible(false);
        formErrorLabel.setManaged(false);
    }

    private void persist() {
        try {
            storage.saveMediTrackData(model.getMediTrack());
        } catch (IOException e) {
            showFormError("Warning: changes could not be saved - " + e.getMessage());
        }
    }
}
